/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poker.practica_op.hja.GUI;

import java.awt.CardLayout;
import logic.Juego;
import logic.Strat;

/**
 *
 * @author jjcar
 */
public class MainFrame extends javax.swing.JFrame {
    
    private enum Turno{ HUMANO, BOT }
    
    private enum InfoType { START, SHOWDOWN, FOLD }
    
    private Turno turno;
    
    private Juego game;
    
    private Strat strat;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "card3");
        strat = Strat.AGRESSIVE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        GamePanel = new javax.swing.JPanel();
        BotPanel = new javax.swing.JPanel();
        Bot_card2 = new javax.swing.JLabel();
        Bot_card1 = new javax.swing.JLabel();
        Bot_blind = new javax.swing.JLabel();
        BoardPanel = new javax.swing.JPanel();
        Flop1 = new javax.swing.JLabel();
        Flop2 = new javax.swing.JLabel();
        Flop3 = new javax.swing.JLabel();
        Turn = new javax.swing.JLabel();
        River = new javax.swing.JLabel();
        Flop_ActionButton = new javax.swing.JToggleButton();
        Turn_ActionButton = new javax.swing.JToggleButton();
        River_ActionButton = new javax.swing.JToggleButton();
        Human_bet = new javax.swing.JLabel();
        Bot_bet = new javax.swing.JLabel();
        Player_panel = new javax.swing.JPanel();
        P_card2 = new javax.swing.JLabel();
        P_card1 = new javax.swing.JLabel();
        Player_blind = new javax.swing.JLabel();
        Pot_label = new javax.swing.JLabel();
        Bot_stack = new javax.swing.JLabel();
        Human_Stack = new javax.swing.JLabel();
        ActionPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Logger = new javax.swing.JLabel();
        ActionButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Bet_slider = new javax.swing.JSlider();
        Bet_button = new javax.swing.JButton();
        Call_button = new javax.swing.JButton();
        Fold_button = new javax.swing.JButton();
        BetText = new javax.swing.JTextField();
        StartPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        PlayButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Agressive_button = new javax.swing.JToggleButton();
        Tight_button = new javax.swing.JToggleButton();
        Balanced_button = new javax.swing.JToggleButton();
        Cheater_Button = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        BotPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        Bot_card2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Bot_card2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        Bot_card1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Bot_card1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Bot_blind.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Bot_blind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bot_blind.setText("BB");

        javax.swing.GroupLayout BotPanelLayout = new javax.swing.GroupLayout(BotPanel);
        BotPanel.setLayout(BotPanelLayout);
        BotPanelLayout.setHorizontalGroup(
            BotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Bot_card1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bot_card2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Bot_blind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BotPanelLayout.setVerticalGroup(
            BotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotPanelLayout.createSequentialGroup()
                .addGroup(BotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bot_card1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(Bot_card2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bot_blind, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        BoardPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Board", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        Flop1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Flop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Flop2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Flop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Flop3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Flop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Turn.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Turn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        River.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        River.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Flop_ActionButton.setBackground(new java.awt.Color(255, 255, 255));
        Flop_ActionButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Flop_ActionButton.setText("Flop");
        Flop_ActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Flop_ActionButtonActionPerformed(evt);
            }
        });

        Turn_ActionButton.setBackground(new java.awt.Color(255, 255, 255));
        Turn_ActionButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Turn_ActionButton.setText("Turn");
        Turn_ActionButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Turn_ActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Turn_ActionButtonActionPerformed(evt);
            }
        });

        River_ActionButton.setBackground(new java.awt.Color(255, 255, 255));
        River_ActionButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        River_ActionButton.setText("River");
        River_ActionButton.setBorder(null);
        River_ActionButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        River_ActionButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        River_ActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                River_ActionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoardPanelLayout = new javax.swing.GroupLayout(BoardPanel);
        BoardPanel.setLayout(BoardPanelLayout);
        BoardPanelLayout.setHorizontalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Flop_ActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BoardPanelLayout.createSequentialGroup()
                        .addComponent(Flop1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Flop2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Flop3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Turn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Turn_ActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(River_ActionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(River, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BoardPanelLayout.setVerticalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(River, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(Turn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Flop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Flop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Flop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Flop_ActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Turn_ActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(River_ActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Human_bet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Human_bet.setText("Bet");

        Bot_bet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Player_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Player", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        P_card2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        P_card2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        P_card1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        P_card1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Player_blind.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Player_blind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player_blind.setText("SB");

        javax.swing.GroupLayout Player_panelLayout = new javax.swing.GroupLayout(Player_panel);
        Player_panel.setLayout(Player_panelLayout);
        Player_panelLayout.setHorizontalGroup(
            Player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(P_card1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(P_card2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Player_blind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Player_panelLayout.setVerticalGroup(
            Player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Player_panelLayout.createSequentialGroup()
                .addGroup(Player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_card1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(P_card2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Player_blind, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        Pot_label.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Pot_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pot_label.setText("Pot");

        Bot_stack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bot_stack.setText("Stack");

        Human_Stack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Human_Stack.setText("Stack");

        ActionPanel.setLayout(new java.awt.CardLayout());

        Logger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logger.setText("Computer Action");

        ActionButton.setText("OK");
        ActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logger, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(ActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logger, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActionButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        ActionPanel.add(jPanel7, "card2");

        Bet_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Bet_sliderStateChanged(evt);
            }
        });

        Bet_button.setText("Bet");
        Bet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bet_buttonActionPerformed(evt);
            }
        });

        Call_button.setText("Call");

        Fold_button.setText("Fold");

        BetText.setText("jTextField1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bet_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BetText)
                    .addComponent(Bet_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Call_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fold_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bet_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bet_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Call_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fold_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        ActionPanel.add(jPanel6, "card1");

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addComponent(Human_bet, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pot_label, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bot_bet, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Player_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Human_Stack, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bot_stack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bot_bet, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Human_bet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Player_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addComponent(Pot_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bot_stack, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Human_Stack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ActionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );

        MainPanel.add(GamePanel, "card2");

        StartPanel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Bot Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        PlayButton.setFont(new java.awt.Font("Dialog", 0, 50)); // NOI18N
        PlayButton.setText("Play");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        Agressive_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Agressive_button.setSelected(true);
        Agressive_button.setText("Agressive");
        Agressive_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agressive_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Agressive_button);

        Tight_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Tight_button.setText("Tight");
        jPanel1.add(Tight_button);

        Balanced_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Balanced_button.setText("Balanced");
        jPanel1.add(Balanced_button);

        Cheater_Button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Cheater_Button.setText("Cheater");
        jPanel1.add(Cheater_Button);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NLHE Heads Up Bot");

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartPanelLayout.setVerticalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(StartPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Flop_ActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Flop_ActionButtonActionPerformed
        // TODO add your handling code here:
        if(Flop_ActionButton.isSelected()){
            //setFlop();
        }else{
            //clearBoard();
        }
    }//GEN-LAST:event_Flop_ActionButtonActionPerformed

    private void Turn_ActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Turn_ActionButtonActionPerformed
        // TODO add your handling code here:
        if(Turn_ActionButton.isSelected()){
            //setTurn();
        }else{
            //clearTurn();
        }
    }//GEN-LAST:event_Turn_ActionButtonActionPerformed

    private void River_ActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_River_ActionButtonActionPerformed
        // TODO add your handling code here:
        if(River_ActionButton.isSelected()){
            //setRiver();
        }else{
            //clearRiver();
        }
    }//GEN-LAST:event_River_ActionButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        // TODO add your handling code here:
        actionPlay();
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void Agressive_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agressive_buttonActionPerformed
        // TODO add your handling code here:
        strat = Strat.AGRESSIVE;
        
    }//GEN-LAST:event_Agressive_buttonActionPerformed

    private void ActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButtonActionPerformed
        // TODO add your handling code here:
        OKActionListener();
    }//GEN-LAST:event_ActionButtonActionPerformed

    private void Bet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bet_buttonActionPerformed
        // TODO add your handling code here:
        betButtonListener();
    }//GEN-LAST:event_Bet_buttonActionPerformed

    private void Bet_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Bet_sliderStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Bet_sliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionButton;
    private javax.swing.JPanel ActionPanel;
    private javax.swing.JToggleButton Agressive_button;
    private javax.swing.JToggleButton Balanced_button;
    private javax.swing.JTextField BetText;
    private javax.swing.JButton Bet_button;
    private javax.swing.JSlider Bet_slider;
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JPanel BotPanel;
    private javax.swing.JLabel Bot_bet;
    private javax.swing.JLabel Bot_blind;
    private static javax.swing.JLabel Bot_card1;
    private static javax.swing.JLabel Bot_card2;
    private javax.swing.JLabel Bot_stack;
    private javax.swing.JButton Call_button;
    private javax.swing.JToggleButton Cheater_Button;
    private javax.swing.JLabel Flop1;
    private javax.swing.JLabel Flop2;
    private javax.swing.JLabel Flop3;
    private javax.swing.JToggleButton Flop_ActionButton;
    private javax.swing.JButton Fold_button;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JLabel Human_Stack;
    private javax.swing.JLabel Human_bet;
    public static javax.swing.JLabel Logger;
    private javax.swing.JPanel MainPanel;
    private static javax.swing.JLabel P_card1;
    private static javax.swing.JLabel P_card2;
    private javax.swing.JButton PlayButton;
    private javax.swing.JLabel Player_blind;
    private javax.swing.JPanel Player_panel;
    private javax.swing.JLabel Pot_label;
    private javax.swing.JLabel River;
    private javax.swing.JToggleButton River_ActionButton;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JToggleButton Tight_button;
    private javax.swing.JLabel Turn;
    private javax.swing.JToggleButton Turn_ActionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

    public void actionPlay(){
        
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "card2");
        
        game = new Juego(strat , true);
        
        if(true){
            turno = Turno.BOT;
            Bot_blind.setText("SB");
            Player_blind.setText("BB");
        }
        
        Logger.setText("Ready to play!");
        
    }
    
    private void OKActionListener(){
        
        switch(turno){
            case BOT:
                CardLayout card2 = (CardLayout)ActionPanel.getLayout();
                card2.show(ActionPanel, "card2");
                
                if(Juego.estado == Juego.estadoPartida.START){
                    game.startGame();
                }
                
                Pot_label.setText(Double.toString(game.getApuestaBot() + game.getApuestaPlayer()));
                
                if(true){
                    game.raiseJugador(1);
                    game.setApuestaPlayer(0);
                }
                
                Human_Stack.setText(Double.toString(game.getPlayer().getFichas()));
                Bot_stack.setText(Double.toString(game.getBot().getFichas()));
                
                Bot_bet.setText(Double.toString(game.getApuestaBot()));
                Human_bet.setText(Double.toString(game.getApuestaPlayer()));
                
                
                P_card1.setText(game.getCartasJugador().get(0).toString());
                P_card2.setText(game.getCartasJugador().get(1).toString());
                /*
                Bot_card1.setText("░");
                Bot_card2.setText("░");
                */
                Bot_card1.setText(game.getCartasBot().get(0).toString());
                Bot_card2.setText(game.getCartasBot().get(1).toString());
                
                turno = Turno.HUMANO;
                break;
            case HUMANO:
                //check estado
                
                card2 = (CardLayout)ActionPanel.getLayout();
                card2.show(ActionPanel, "card1");
                
                Bet_slider.setMaximum((int)game.getBot().getFichas());
                Bet_slider.setMinimum((int)game.getApuestaBot());
                
                turno = Turno.BOT;
                break;
        }   
    }

    private void betButtonListener(){
        
        Pot_label.setText(Double.toString(game.getApuestaBot() + game.getApuestaPlayer()));
        
        game.raiseJugador(Double.parseDouble(BetText.getText()));
        
        
        CardLayout card2 = (CardLayout)ActionPanel.getLayout();
        card2.show(ActionPanel, "card2");
                
        turno = Turno.BOT;
    }
    
    private void refreshGUI(){
        
        Bot_bet.setText(Double.toString(game.getApuestaBot()));
        Human_bet.setText(Double.toString(game.getApuestaPlayer()));
        
        Human_Stack.setText(Double.toString(game.getPlayer().getFichas()));
        Bot_stack.setText(Double.toString(game.getBot().getFichas()));
        
    }
    
    private void preflopGUI(){
        
        Pot_label.setText(Double.toString(0));
        
        P_card1.setText(game.getCartasJugador().get(0).toString());
        P_card2.setText(game.getCartasJugador().get(1).toString());
        /*
        Bot_card1.setText("░");
        Bot_card2.setText("░");
        */
        Bot_card1.setText(game.getCartasBot().get(0).toString());
        Bot_card2.setText(game.getCartasBot().get(1).toString());
        
        refreshGUI();
    }
    
    private void flopGUI(){
        
        Pot_label.setText(Double.toString( game.getBote() +
                game.getApuestaBot() + game.getApuestaPlayer()));
        
        Flop1.setText(game.getBoard().get(0).toString());
        Flop2.setText(game.getBoard().get(1).toString());
        Flop3.setText(game.getBoard().get(2).toString());
        
        refreshGUI();
    }
    
    private void turnGUI(){
        
        Pot_label.setText(Double.toString( game.getBote() +
                game.getApuestaBot() + game.getApuestaPlayer()));
        
        Turn.setText(game.getBoard().get(3).toString());
        
        refreshGUI();
    }
    
    private void riverGUI(){
        
        Pot_label.setText(Double.toString( game.getBote() +
                game.getApuestaBot() + game.getApuestaPlayer()));
        
        River.setText(game.getBoard().get(4).toString());
        
        refreshGUI();
    }
    
    private void infoGUI(InfoType info){
        
        Pot_label.setText("");
        
        Bot_bet.setText("");
        Human_bet.setText("");
        
        Human_Stack.setText(Double.toString(game.getPlayer().getFichas()));
        Bot_stack.setText(Double.toString(game.getBot().getFichas()));
        
        switch (info){
            case START:
                Logger.setText("Ready To play!");
            case SHOWDOWN:
                Logger.setText("Someone Wins!");
            case FOLD:
                Logger.setText("Someone folded");
        }    
    }
    
    
    

}

    
